Shouqun/node-dbus

lib/bus.js
It was "usr strict" - changed it to "use strict".
=> Fix strict statement in bus.js

lib/bus.js
This fix attaches each signal handler to the unique dbus connection ID (obtained with [getNameOwner](http://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-get-name-owner)).
See issue #71.
=> Only attach signal handler to a single connection

src/encoder.cc
Double could never be reached because uint32 caught it beforehand
=> fix never getting double, even if it should be one

src/connection.cc, src/dbus.cc, src/object_handler.cc, src/signal.cc
Please pull the following changesets to fix the build against nodejs v0.10.x
- use `Handle<Value>` rather than `Local<Value>` where appropriate
- fix return-statement with no value, in function returning `v8::Handle<v8::Value>`
- replace `True` with `true` and `False` with `false`
All three patches are required in order to build against nodejs v0.10.x
Tested against nodejs v0.10.26 and nodejs v0.12.4
=> fix build against nodejs v0.10.x

src/introspect.cc
Without this patch no list is created from the output arguments. This is
different from how the input arguments are handled. Only the last output argument
is then seen in the introspection, what is wrong.
=> introspect: create an ouput argument array

src/connection.cc
If a lot of data is transfered over D-Bus it is possible that
watch_handle is called with a watch that was never added. This handle
can then have a file descriptor, that already belongs to an other watch.
If watch_add ist called in this scenario, an new uv watcher will be
created. This then crashes libuv.
output of a debugging session:
watch_add
watch_add
fd: 9
Watch pt: 0x3377a60 // Watch for fd 9 added
// Here the problem starts:
watch_handle
// This watch was never added!
Watch pt: 0x3377a10
// Add it now
watch_add
fd: 9
Watch pt: 0x3377a10
// Crash because watch with pt 0x3377a60 is already registered for fd 9
node: ../deps/uv/src/unix/core.c:855: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
Aborted
=> connection.cc: don't add two watchers for one fd

src/dbus.cc, src/decoder.cc, src/decoder.h, src/object_handler.cc, src/signal.cc
use `Local<Value>` rather than `Handle<Value>` where appropriate
fixes a build breakage using nan 2.1.0 and nodejs v0.10.x
tested against nodejs v0.10.29 & v0.12.2
fixes #108
=> fix build using nan 2.1.0 against nodejs v0.10.x

lib/service_interface.js
I think the if is not necessary because prop['in'] is never set for properties.
=> Always add the value as argument for the property setter.

src/connection.cc, src/dbus.cc, src/dbus.h, src/decoder.cc, src/encoder.cc, src/encoder.h, src/object_handler.cc, src/signal.cc, src/signal.h
Fix DispatchSignal symbol not found when loading the module. The declaration in src/signal.h and the implementation of the DispatchSignal method in src/signal.cc, so the symbol could not be found.
Remove usage of the deprecated v8::Handle class.
Remove uneeded HandleScope.
=> Fix DispatchSignal symbol not found when loading the module

lib/bus.js, lib/dbus.js
I have fixed the following in this PR:
- Adds service name when registering for signal.
- Removes sender unique name comparison from signal hash.
- Removes unused call to add signal interface.
Closes issue #113
=> Fixes lost singals when dbus service restarts

src/encoder.cc
encoder: fix arrays of items of the same type
As described in https://github.com/Shouqun/node-dbus/issues/120
A javascript array is always handled as an array of variant.
This steps through an array to confirm that all elements are of the same type,
then produces a dbus structure accordingly, now supporting:
* array of boolean
* array of byte
* array of uint32
* array of int32
* array of double
* array of string
* array of array (variant)
* array of object
and defaulting to array of variant otherwise.
Please note:  The function tries the above data types in exactly the above order, just as node-dbus already does for its data type detection.  For example, if all of the elements pass for `byte`, then they will be passed as an `array of byte`.  If one of the elements do not pass as a `byte`, …
=> encoder: fix arrays of same item type

src/encoder.cc
Please merge these changes to clean up the code that was added to fix the marshaling of arrays with items of the same type #121 as described in #120
=> encoder: refactor array handling to reuse common code

src/encoder.cc, src/encoder.h
In the spirit of #120 , this fixes the handling of the case of `nested arrays` where each internal array contains items all of the same type by allowing the function `GetSignatureFromV8Type` to call itself recursively.
For example, when encoding the following:
```
[ [ [ 'X', 'Y' ], [ 'a', 'bb', 'ccc' ] ],
[ [ 'X', 'Y' ], [ 'a', 'bb', 'ccc' ] ],
[ [ 'X', 'Y' ], [ 'a', 'bb', 'ccc' ] ] ]
```
build `0.2.18` returns:
```
variant       array [
array [
variant                array [
string "X"
string "Y"
]
variant                array [
string "a"
string "bb"
string "ccc"
]
]
array [
variant                array [
string "X"
string "Y"
]
variant                array [
string "a"
string "bb"
string "ccc"
]
]
array [
variant                array [
string "X"
string "Y"
]
variant …
```
=> encoder: fix marshalling of nested arrays

src/decoder.cc
This is especially important when dealing with signed vs. unsigned types.
=> Use the correct variable type when parsing message

README.md, binding.gyp
Fixes issue #144, allowing node-dbus to built on MacOS X.
Tested with latest dbus installed via MacPorts 2.3.5, on MacOS X 10.12.2, and node 6.7.0.
=> Allow for building on MacOS X 10.12.2 with MacPorts

lib/service_object.js
Add `<node name="[child_path]"/>` to the introspection XML for all
potential child paths that have already been defined. This makes it
possible to find the children of a path using tools like `busctl tree`.
Fixes #149
=> Allow child paths to be introspectable

.gitignore, .travis.yml, lib/.travis.yml, package.json, test/client-call-add.test.js, test/client-call-noargs.test.js, test/client-call-timeout.test.js, test/client-call.test.js, test/client-property.test.js, test/client-signal.test.js, test/service.js, test/with-service.js
Based on the .travis.yml, it looks like this project supports back to Node 0.12.
While doing the work for pull request #150, I used `Object.keys`. However, I was unsure whether this was a supported call in Node 0.12. Because the Travis-CI build only tests whether the C++ code builds propertly, and doesn't test any of the JS code, the results of the Travis-CI build doesn't prevent code that would break in Node 0.12 from getting committed.
So, this commit adds some basic tests (cribbed mostly from the examples folder) that run a service and a client against an actual dbus daemon to test that the code can do basic things like call methods, get and set properties, and receive signals.
The way this is done is that, each test file (`test/*.test.js`) spawns a DBus Service (`test/service.js`) and …
=> Add basic tests against dbus

.gitignore, .travis.yml, examples/error_handling.js, examples/hello.js, examples/invalid_args.js, examples/method.js, examples/multi_connection.js, lib/.travis.yml, lib/interface.js, package.json, test/client-call-add.test.js, test/client-call-noargs.test.js, test/client-call-timeout.test.js, test/client-property.test.js, test/client-signal.test.js, test/service.js, test/with-service.js
Change how methods are called on an interface from
iface.someMethod.timeout = 1000;
iface.someMethod.error = function(err) {
};
iface.someMethod.finish = function(result) {
};
iface.someMethod(arg1, arg2);
to
iface.someMethod(arg1, arg2, {timeout:1000}, function(err, result) {
});
or (if the timeout is not needed, the options object can be dropped)
iface.someMethod(arg1, arg2, function(err, result) {
});
to be more in-line with node's error-first callback conventions around
asynchronous calls.
Fixes #86.
=> Use node conventions for asynchronous calls

README.md, lib/bus.js, lib/dbus.js, lib/interface.js, lib/service.js, lib/service_interface.js, src/connection.cc, test/client-call-add.test.js, test/client-call-noargs.test.js, test/client-call-timeout.test.js, test/client-disconnect.test.js, test/client-property.test.js, test/client-signal.test.js, test/client-use-after-disconnect.test.js, test/service-client-disconnect.test.js, test/service-create-remove-object.test.js, test/service-disconnect.test.js, test/service-dynamic.js, test/service-emit-after-disconnect.test.js, test/service.js, test/with-service.js
Allow applications to disconnect their connections to dbus after they are done with them.
Fixes #133
Changes required to make this happen:
* Don't share bus objects: remove the code in lib/dbus.js that stores created Bus objects and returns them when a new bus is requested. Instead, create a new Bus object whenever one is requested. This allows each Bus object to disconnect itself without worrying that other objects are relying on it being connected. Note that at the C++ level, there is connection sharing going on because of the use of `dbus_bus_get`, but that isn't a problem because the dbus library is managing the sharing, and calling `Bus.prototype.disconnect` will correctly notify the underlying C++ that that particulary Bus object is no longer using its connection.
* Remove the …
=> Add bus.disconnect and service.disconnect

README.md, examples/service.js, lib/dbus.js, lib/error.js, lib/interface.js, lib/service_interface.js, src/dbus.cc, src/dbus.h, test/client-call-error.test.js, test/client-property-error.test.js, test/client-property.test.js, test/error.test.js, test/service-create-remove-object.test.js, test/service.js
From what I could tell, when a DBus service returned an error, this would be surfaced to this library as `new Error(errorName)`, with no way to get access to the error message. Similarly, when a service created by this library wanted to return an error instead of a value from a method call, it would have to return a `new Error(errorName)` with no way to set the error message.
These commits fix that by making it possible to retrieve (when receiving an error from a service) and specify (when implementing a service) both the error name and error message.
This is done via a new `DBus.Error` class which has a `dbusName` property that contains the name of the error. The regular `message` property of the error contains the human-readable message (which is a change from previous, where the …
=> Error class

examples/service.js, lib/service_interface.js, lib/service_object.js, test/client-call-error.test.js, test/client-call-object.test.js, test/client-property-error.test.js, test/service-dynamic.js, test/service.js
For methods and properties defined by a service, use node-style callbacks for the results, which means that the callback takes an error as the first value or the result as the second value.
interface.addMethod('Method', {}, function handler(callback) {
callback(new DBus.Error('dbus.test.Error', 'Method threw error'));
// or
callback(null, 'This is the result');
});
This change makes it possible to pass the callback directly into other APIs that expect node-style callbacks.
const fs = require('fs');
interface.addMethod(
'StealPasswords',
{ out: [DBus.Define(String)] },
function(callback) {
fs.readFile('/etc/password', { encoding: 'utf8' }, callback);
}
);
=> Use node-style callbacks for methods and properties

README.md, examples/error_handling.js, examples/get_property.js, examples/hello.js, examples/invalid_args.js, examples/method.js, examples/multi_connection.js, examples/service.js, examples/set_max_received_size.js, examples/signal.js, lib/bus.js, lib/dbus.js, lib/interface.js, lib/service.js, lib/service_interface.js, test/client-call-add.test.js, test/client-call-error.test.js, test/client-call-noargs.test.js, test/client-call-timeout.test.js, test/client-disconnect.test.js, test/client-property-error.test.js, test/client-property.test.js, test/client-signal.test.js, test/client-use-after-disconnect.test.js, test/service-client-disconnect.test.js, test/service-create-remove-object.test.js, test/service-disconnect.test.js, test/service-dynamic.js, test/service-emit-after-disconnect.test.js, test/service.js
The DBus class does not really have any usable instance data, so from an API perspective, it doesn't make much sense to create an instance of DBus just so that we can create an instance of Bus or Service.
So instead, make `getBus` and `registerService` static methods that can be called directly, without instantiating a DBus instance first. This simplifies the calling code a little bit.
That means that
var dbus = new DBus();
var bus = dbus.getBus('session');
turns into
var bus = DBus.getBus('session');
and
var dbus = new DBus();
var service = dbus.registerService('session', 'service.name');
turns into
var service = DBus.registerService('session', 'service.name');
Note that for backwards compatibility reasons, it's still possible to instantiate a new instance and call the methods on the …
=> Change DBus entry points to be static

MIGRATING.md, README.md, package.json
Major breaking API changes happened in PRs #153, #161, and #163.
According to semver, there should be a major version number bump because of those changes.
(I also added myself to the contributors. I hope that's not too forward.)
=> Bump version to 1.0.0

src/encoder.cc, test/client-call-intdict.test.js, test/service.js
DBus allows dictionary encodings using any primitive type as key.  This adds support for dictionaries with non-string keys.
=> Adding support for encoding dictionaries with non-string keys

lib/interface.js, src/dbus.cc, src/encoder.cc, src/encoder.h, src/object_handler.cc, src/signal.cc, test/client-call-intdict.test.js, test/service.js
When setting properties, the implementation in terms of the 'Set' method currently does not respect the declared type of the property, because the 'Set' method argument is encoded as a variant.  This adds an extra parameter to the EncodeObject which allows a caller to indicate the concrete type to use to encode variants, and uses this capability to correctly encode property writes.
This builds on the changes in #174, but not in an essential way - I just wanted to make merging easier because I knew they would conflict otherwise.
Unfortunately, I am not aware of a good way to automate testing of the wire encoding from within Javascript, or familiar enough with the Javascript build and test tools to integrate C or C++ code into the test suite, but I have tested this against live DBus …
=> Set property strict encoding

binding.gyp
Before this patch, `ld` would error that it could not find the `dylib` file on macOS. This fixes the issue
=> Fix linking error on macOS

lib/dbus.js, src/dbus.cc, src/object_handler.cc, test/service-duplicate-error.test.js
Currently there was a couple of spots where error handling with regards to existing services and objects was being ignored, which caused stray printf's and unresponsive services. I also think that deferring `DBus._requestName` to the next tick may be nice, but it makes it impossible to catch the error being thrown and handle it in a graceful way. This may be a semver major bump, since registerService now will be blocking
=> Better error handling for taken objects and names

src/decoder.cc, src/encoder.cc
This adds support of `DBUS_TYPE_UNIX_FD` as suggested in #134 
FDs are handled just like normal integers.
=> Add support for UNIX_FD

lib/service.js
After removing the object from the service on the bus, the Service was
still holding a reference in its internal cache, causing introspection
to list the object when it didn't exist anymore.
=> Remove object from cache when unregistered

.gitignore, package.json, src/connection.cc, src/dbus.cc, src/decoder.cc, src/encoder.cc, src/encoder.h, src/introspect.cc, src/object_handler.cc, src/signal.cc
sending null or undefined values leads to emit `SIGSEGV` signal
=> fix: prevent sending null and undefined

lib/service_interface.js
This patch add a 'return self;' to each functions in service_interface
module to use method chaining technique. This helps developers write
code more conveniently. Please refer to the example below.
var obj = service.createObject('/test');
obj.createInterface('test.iface')
.addMethod('method1', ...)
.addMethod('method2', ...)
.update();
Signed-off-by: Inho Oh <webispy@gmail.com>
=> Add return self to service_interface

src/dbus.cc
Add NAN_MODULE_WORKER_ENABLED macro as a replacement for NAN_MODULE.
Closes Shouqun/node-dbus#212
=> Support worker threads

lib/bus.js
The current `Bus.prototype.reconnect` throws if we call it after `Bus.prototype.disconnect` because it nulls out the `self.connection` object.
=> Bus.prototype.reconnect to handle null connection

lib/service_interface.js, lib/service_object.js
In some scenario, addProperty does not send correct data to `DBus`.  For example, in bluez api, ManufacturerData's dict key must be uint16), but JS does not support number-type key. Since`out` value was forced to set to `Utils.Define('Auto', 'value')` in when implementing `org.freedesktop.DBus.Properties`, the returned value's `prop_key` was mis-transformed to `string`.
This PR introduced function support when defining method, so value type could be dynamic returned according args.
=> Add callback function support to callMethod in/out defs.
